export const ROUTE_CHANGE = "ROUTE_CHANGE";

/**
 * USER ACTIONS
 */

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

/**
 * AUTHENTICATION ACTIONS
 */

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

/**
 * USER BOOKMARK ACTIONS
 */

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const REMOVE_USER_REQUEST = "REMOVE_USER_REQUEST";
export const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS";
export const REMOVE_USER_FAILURE = "REMOVE_USER_FAILURE";

/**
 * SCHOOL ACTIONS
 */

export const FETCH_SCHOOLS_REQUEST = "FETCH_SCHOOLS_REQUEST";
export const FETCH_SCHOOLS_SUCCESS = "FETCH_SCHOOLS_SUCCESS";
export const FETCH_SCHOOLS_FAILURE = "FETCH_SCHOOLS_FAILURE";

/**
 * MAJOR ACTIONS
 */

export const FETCH_MAJORS_REQUEST = "FETCH_MAJORS_REQUEST";
export const FETCH_MAJORS_SUCCESS = "FETCH_MAJORS_SUCCESS";
export const FETCH_MAJORS_FAILURE = "FETCH_MAJORS_FAILURE";
