export const ROUTE_CHANGE = "ROUTE_CHANGE";

// FETCH_USER_REQUEST
// FETCH_USER_SUCCESS
// FETCH_USER_FAILURE

export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_FAILURE = "USER_INFO_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const BOOKMARK_USER_REQUEST = "BOOKMARK_USER_REQUEST";
export const BOOKMARK_USER_SUCCESS = "BOOKMARK_USER_SUCCESS";
export const BOOKMARK_USER_FAILURE = "BOOKMARK_USER_FAILURE";
